# This file was generated by the Tkinter Designer by Parth Jadhav
# Logic developed by Anakin-bb8
# Granted under the MIT License

from pathlib import Path
import ctypes
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox, filedialog
import tkinter as tk
import os

os.system("cd NPTEUpdatingSystem && start ./NPTEUpdatingSystem.exe")

python_file_name = None

def select_py_file():
    filename = filedialog.askopenfilename(filetypes=(("Python files", "*.py"), ("All files", "*.*")))
    entry_7.delete(0, tk.END) 
    entry_7.insert(0, filename)
    global python_file_name
    python_file_name = Path(filename).stem

def select_ico_file():
    fileico = filedialog.askopenfilename(filetypes=(("Windows icon", "*.ico"), ("All files", "*.*")))
    entry_5.delete(0, tk.END)
    entry_5.insert(0, fileico)

def select_folder():
    directory = filedialog.askdirectory()
    entry_8.delete(0, tk.END)
    entry_8.insert(0, directory)

def build():
    name = entry_1.get()
    version = entry_2.get()
    description = entry_3.get()
    author = entry_4.get()
    tkinter_use = entry_6.get().lower()
    pyfile = entry_7.get()
    icofile = entry_5.get()
    output = entry_8.get().replace("/", "\\")

    if not all([name, version, description, author, tkinter_use, pyfile, output]):
        messagebox.showerror("Error", "Missing informations")
        return
    
    main = [f'echo off && cls\ncd "{output}"\npython -m nuitka --product-name="{name}" --output-filename="{name}" --file-version={version} --company-name="{author}" --standalone "{pyfile}"']
    
    

    if tkinter_use == "y":
        main.append(" --enable-plugin=tk-inter")
        terminal = messagebox.askyesno("Terminal usage","Do you wish to disable the terminal while running your app?")

        if terminal:
            main.append(" --windows-console-mode=disable")
    
    if icofile:
        main.append(f' --windows-icon-from-ico="{icofile}"')
    
    
    result = " ".join(main)
    
    code_parts = [
        result
    ]

    code_parts.append(f'rmdir /s /q "{output}\\{python_file_name}.build"')
    code_parts.append('pause')
    code_parts.append(f'del "{output}\\Build.bat"')

    code = '\n'.join(code_parts)

    with open(f'{output}/Build.bat', 'w') as my_bat:
        my_bat.write(code)

    success = messagebox.askyesno("Success!", f"The file 'Build.bat' was built successfully at {output}, do you wish to run it?")

    if success:
        os.system(f'start "{output}\\Build.bat"')



ctypes.windll.shcore.SetProcessDpiAwareness(1)
OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title("NPTE")
window
icon_image = tk.PhotoImage(file=ASSETS_PATH / "icon.png")
window.wm_iconphoto(True, icon_image)
window.geometry("1000x847")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 847,
    width = 1000,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    252.0,
    275.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    756.0,
    275.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    756.0,
    401.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    756.0,
    536.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    252.0,
    401.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    252.0,
    536.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    252.0,
    666.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    757.0,
    665.0,
    image=image_image_8
)

canvas.create_text(
    110.0,
    30.0,
    anchor="nw",
    text="NPTE - Nuitka Python to Executables",
    fill="#000000",
    font=("Poppins Medium", 30 * -1)
)

canvas.create_text(
    29.0,
    121.0,
    anchor="nw",
    text="Enter details:",
    fill="#000000",
    font=("Poppins Medium", 35 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: build(),
    cursor="hand2",
    relief="flat"
)
button_1.place(
    x=307.61871337890625,
    y=736.4310302734375,
    width=392.3907470703125,
    height=99.5689697265625
)

button_image_hover_1 = PhotoImage(
    file=relative_to_assets("button_hover_1.png"))

def button_1_hover(e):
    button_1.config(
        image=button_image_hover_1
    )
def button_1_leave(e):
    button_1.config(
        image=button_image_1
    )

button_1.bind('<Enter>', button_1_hover)
button_1.bind('<Leave>', button_1_leave)


canvas.create_text(
    29.0,
    191.0,
    anchor="nw",
    text="Product name:",
    fill="#000000",
    font=("Poppins Medium", 30 * -1)
)

canvas.create_text(
    525.0,
    318.0,
    anchor="nw",
    text="Python File:",
    fill="#000000",
    font=("Poppins Medium", 30 * -1)
)

canvas.create_text(
    525.0,
    456.0,
    anchor="nw",
    text="Output folder:",
    fill="#000000",
    font=("Poppins Medium", 30 * -1)
)

canvas.create_text(
    525.0,
    191.0,
    anchor="nw",
    text="Does your program use tkinter? [y/n]",
    fill="#000000",
    font=("Poppins Medium", 21 * -1)
)

canvas.create_text(
    29.0,
    318.0,
    anchor="nw",
    text="File Version:",
    fill="#000000",
    font=("Poppins Medium", 35 * -1)
)

canvas.create_text(
    29.0,
    456.0,
    anchor="nw",
    text="File Description:",
    fill="#000000",
    font=("Poppins Medium", 30 * -1)
)

canvas.create_text(
    29.0,
    591.0,
    anchor="nw",
    text="Author:",
    fill="#000000",
    font=("Poppins Medium", 30 * -1)
)

canvas.create_text(
    525.0,
    591.0,
    anchor="nw",
    text="Icon path (optional):",
    fill="#000000",
    font=("Poppins Medium", 25 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    243.0,
    276.5,
    image=entry_image_1
)
entry_1 = Entry(
    font=("Poppins", 25 * -1),
    bd=0,
    bg="#F9F6F6",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=43.0,
    y=257.0,
    width=400.0,
    height=37.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    243.0,
    400.0,
    image=entry_image_2
)
entry_2 = Entry(
    font=("Poppins", 25 * -1),
    bd=0,
    bg="#F9F6F6",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=43.0,
    y=381.0,
    width=400.0,
    height=36.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    243.0,
    537.0,
    image=entry_image_3
)
entry_3 = Entry(
    font=("Poppins", 25 * -1),
    bd=0,
    bg="#F9F6F6",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=43.0,
    y=518.0,
    width=400.0,
    height=36.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    243.0,
    666.0,
    image=entry_image_4
)
entry_4 = Entry(
    font=("Poppins", 25 * -1),
    bd=0,
    bg="#F9F6F6",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=43.0,
    y=646.0,
    width=400.0,
    height=38.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    733.0,
    665.5,
    image=entry_image_5
)
entry_5 = Entry(
    font=("Poppins", 25 * -1),
    bd=0,
    bg="#F9F6F6",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=548.0,
    y=646.0,
    width=370.0,
    height=37.0
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    752.0,
    274.0,
    image=entry_image_6
)
entry_6 = Entry(
    font=("Poppins", 25 * -1),
    bd=0,
    bg="#F9F6F6",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=552.0,
    y=254.0,
    width=400.0,
    height=38.0
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    733.0,
    401.5,
    image=entry_image_7
)
entry_7 = Entry(
    font=("Poppins", 25 * -1),
    bd=0,
    bg="#F9F6F6",
    fg="#000716",
    highlightthickness=0
)
entry_7.place(
    x=548.0,
    y=382.0,
    width=370.0,
    height=37.0
)

entry_image_8 = PhotoImage(
    file=relative_to_assets("entry_8.png"))
entry_bg_8 = canvas.create_image(
    733.0,
    535.0,
    image=entry_image_8
)
entry_8 = Entry(
    font=("Poppins", 25 * -1),
    bd=0,
    bg="#F9F6F6",
    fg="#000716",
    highlightthickness=0
)
entry_8.place(
    x=548.0,
    y=516.0,
    width=370.0,
    height=36.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: select_py_file(),
    cursor="hand2",
    relief="flat"
)
button_2.place(
    x=927.0,
    y=381.0,
    width=48.0,
    height=38.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: select_folder(),
    cursor="hand2",
    relief="flat"
)
button_3.place(
    x=927.0,
    y=516.0,
    width=48.0,
    height=38.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: select_ico_file(),
    cursor="hand2",
    relief="flat"
)
button_4.place(
    x=927.0,
    y=645.0,
    width=48.0,
    height=39.0
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    47.0,
    49.0,
    image=image_image_9
)
window.resizable(False, False)
window.mainloop()
